# Generated by Django 4.2.20 on 2025-03-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_court_field_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='field_type',
            new_name='court_type',
        ),
    ]
