# Generated by Django 4.2.20 on 2025-03-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['-created_on']},
        ),
    ]
