# Generated by Django 4.2.20 on 2025-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
