# Generated by Django 4.2.20 on 2025-03-14 14:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0007_court_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
